/**
 * generated by Xtext 2.23.0
 */
package fr.n7.pDL.impl;

import fr.n7.pDL.DependanceFinish;
import fr.n7.pDL.DependanceStart;
import fr.n7.pDL.Guidance;
import fr.n7.pDL.PDLFactory;
import fr.n7.pDL.PDLPackage;
import fr.n7.pDL.ProcessElement;
import fr.n7.pDL.WorkDefinition;
import fr.n7.pDL.WorkSequenceKindFinish;
import fr.n7.pDL.WorkSequenceKindStart;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class PDLFactoryImpl extends EFactoryImpl implements PDLFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static PDLFactory init()
  {
    try
    {
      PDLFactory thePDLFactory = (PDLFactory)EPackage.Registry.INSTANCE.getEFactory(PDLPackage.eNS_URI);
      if (thePDLFactory != null)
      {
        return thePDLFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new PDLFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PDLFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case PDLPackage.PROCESS: return createProcess();
      case PDLPackage.PROCESS_ELEMENT: return createProcessElement();
      case PDLPackage.WORK_DEFINITION: return createWorkDefinition();
      case PDLPackage.DEPENDANCE_START: return createDependanceStart();
      case PDLPackage.WORK_SEQUENCE_KIND_START: return createWorkSequenceKindStart();
      case PDLPackage.DEPENDANCE_FINISH: return createDependanceFinish();
      case PDLPackage.WORK_SEQUENCE_KIND_FINISH: return createWorkSequenceKindFinish();
      case PDLPackage.GUIDANCE: return createGuidance();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public fr.n7.pDL.Process createProcess()
  {
    ProcessImpl process = new ProcessImpl();
    return process;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ProcessElement createProcessElement()
  {
    ProcessElementImpl processElement = new ProcessElementImpl();
    return processElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WorkDefinition createWorkDefinition()
  {
    WorkDefinitionImpl workDefinition = new WorkDefinitionImpl();
    return workDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DependanceStart createDependanceStart()
  {
    DependanceStartImpl dependanceStart = new DependanceStartImpl();
    return dependanceStart;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WorkSequenceKindStart createWorkSequenceKindStart()
  {
    WorkSequenceKindStartImpl workSequenceKindStart = new WorkSequenceKindStartImpl();
    return workSequenceKindStart;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DependanceFinish createDependanceFinish()
  {
    DependanceFinishImpl dependanceFinish = new DependanceFinishImpl();
    return dependanceFinish;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WorkSequenceKindFinish createWorkSequenceKindFinish()
  {
    WorkSequenceKindFinishImpl workSequenceKindFinish = new WorkSequenceKindFinishImpl();
    return workSequenceKindFinish;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Guidance createGuidance()
  {
    GuidanceImpl guidance = new GuidanceImpl();
    return guidance;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PDLPackage getPDLPackage()
  {
    return (PDLPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static PDLPackage getPackage()
  {
    return PDLPackage.eINSTANCE;
  }

} //PDLFactoryImpl
