/**
 * generated by Xtext 2.23.0
 */
package fr.n7.pDL1;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ressource Used</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.RessourceUsed#getWorkdefinition <em>Workdefinition</em>}</li>
 *   <li>{@link fr.n7.pDL1.RessourceUsed#getOcc <em>Occ</em>}</li>
 *   <li>{@link fr.n7.pDL1.RessourceUsed#getRessources <em>Ressources</em>}</li>
 * </ul>
 *
 * @see fr.n7.pDL1.PDL1Package#getRessourceUsed()
 * @model
 * @generated
 */
public interface RessourceUsed extends ProcessElement
{
  /**
   * Returns the value of the '<em><b>Workdefinition</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Workdefinition</em>' reference.
   * @see #setWorkdefinition(WorkDefinition)
   * @see fr.n7.pDL1.PDL1Package#getRessourceUsed_Workdefinition()
   * @model
   * @generated
   */
  WorkDefinition getWorkdefinition();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.RessourceUsed#getWorkdefinition <em>Workdefinition</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Workdefinition</em>' reference.
   * @see #getWorkdefinition()
   * @generated
   */
  void setWorkdefinition(WorkDefinition value);

  /**
   * Returns the value of the '<em><b>Occ</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Occ</em>' attribute.
   * @see #setOcc(int)
   * @see fr.n7.pDL1.PDL1Package#getRessourceUsed_Occ()
   * @model
   * @generated
   */
  int getOcc();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.RessourceUsed#getOcc <em>Occ</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Occ</em>' attribute.
   * @see #getOcc()
   * @generated
   */
  void setOcc(int value);

  /**
   * Returns the value of the '<em><b>Ressources</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ressources</em>' reference.
   * @see #setRessources(Ressource)
   * @see fr.n7.pDL1.PDL1Package#getRessourceUsed_Ressources()
   * @model
   * @generated
   */
  Ressource getRessources();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.RessourceUsed#getRessources <em>Ressources</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ressources</em>' reference.
   * @see #getRessources()
   * @generated
   */
  void setRessources(Ressource value);

} // RessourceUsed
