/**
 * generated by Xtext 2.23.0
 */
package fr.n7.pDL1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ressource Used</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.RessourceUsed#getOcc <em>Occ</em>}</li>
 *   <li>{@link fr.n7.pDL1.RessourceUsed#getRessourceUsed <em>Ressource Used</em>}</li>
 * </ul>
 *
 * @see fr.n7.pDL1.PDL1Package#getRessourceUsed()
 * @model
 * @generated
 */
public interface RessourceUsed extends EObject
{
  /**
   * Returns the value of the '<em><b>Occ</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Occ</em>' attribute.
   * @see #setOcc(int)
   * @see fr.n7.pDL1.PDL1Package#getRessourceUsed_Occ()
   * @model
   * @generated
   */
  int getOcc();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.RessourceUsed#getOcc <em>Occ</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Occ</em>' attribute.
   * @see #getOcc()
   * @generated
   */
  void setOcc(int value);

  /**
   * Returns the value of the '<em><b>Ressource Used</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ressource Used</em>' reference.
   * @see #setRessourceUsed(Ressource)
   * @see fr.n7.pDL1.PDL1Package#getRessourceUsed_RessourceUsed()
   * @model
   * @generated
   */
  Ressource getRessourceUsed();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.RessourceUsed#getRessourceUsed <em>Ressource Used</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ressource Used</em>' reference.
   * @see #getRessourceUsed()
   * @generated
   */
  void setRessourceUsed(Ressource value);

} // RessourceUsed
