/**
 * generated by Xtext 2.23.0
 */
package fr.n7.pDL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.n7.pDL.PDLPackage#getProcessElement()
 * @model
 * @generated
 */
public interface ProcessElement extends EObject
{
} // ProcessElement
