/*
 * generated by Xtext 2.23.0
 */
package fr.n7.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PDL2UiModule extends AbstractPDL2UiModule {

	public PDL2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
